### ISSUE TITLE
Consider moving NPM package

### ISSUE THREAD

**Issue by steveoh** [agrc/firebase-auth-arcgis-server-proxy#159]
It would be nice to have all of our npm packages in the ugrc namespace. This seems to be one of the last relevant packages not in the namespace.

What are your thoughts on renaming this package during the electrofishing project?

**Comment by stdavis** [comment]
I hadn't realized that this package was not in our namespace. Let's do it. Do we just [deprecate](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#using-the-command-line) the old name and then publish the new name?

**Comment by steveoh** [comment]
Yeah that could work

**Comment by stdavis** [comment]
The new packages is up: https://www.npmjs.com/package/@ugrc/firebase-auth-arcgis-server-proxy

And I marked the old package as deprecated: https://www.npmjs.com/package/firebase-auth-arcgis-server-proxy
